### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by kd4zay** [vulnersCom/getsploit#12]
Hi, 
I get the following when issuing the following command: getsploit -u:
is this an error handling routine issue? 

Downloading getsploit database archive. Please wait, it may take time. Usually around 5-10 minutes.
 39084032/336659441 [11.61%]Traceback (most recent call last):
  File "/usr/local/bin/getsploit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/getsploit/getsploit.py", line 731, in main
    downloadVulnersGetsploitDB(DBPATH)
  File "/usr/local/lib/python2.7/dist-packages/getsploit/getsploit.py", line 636, in downloadVulnersGetsploitDB
    downloadFile(vulnersURL['updateAPI'], archiveFileName, progress_callback=progress_callback_simple)
  File "/usr/local/lib/python2.7/dist-packages/getsploit/getsploit.py", line 608, in downloadFile
    _download_helper(response,out_file,file_size)
  File "/usr/local/lib/python2.7/dist-packages/getsploit/getsploit.py", line 590, in _download_helper
    buffer = response.read(block_size)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 597, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer

**Comment by vulnersCom** [comment]
Oh, I think that was just an network error issue.
We’ve had a lot of deploys this days.

**Comment by kd4zay** [comment]
is there anyway to compensate for slower network or latency ?

Jesus Cabrera

**Comment by vulnersCom** [comment]
That was a problem at our server side.
Whet you were downloading it we restarted Vulners app I think.
