### ISSUE TITLE
Issue with local update

### ISSUE THREAD

**Issue by vulnz** [vulnersCom/getsploit#20]
la-la-2:getsploit none$ getsploit --update
Downloading getsploit database archive. Please wait, it may take time. Usually around 5-10 minutes.
[################################] 276048/427041 - 00:01:35

Unpacking database.
Traceback (most recent call last):
  File "/Users/none/.pyenv/versions/3.6.5/bin/getsploit", line 11, in <module>
    load_entry_point('getsploit==0.3.3', 'console_scripts', 'getsploit')()
  File "/Users/none/.pyenv/versions/3.6.5/lib/python3.6/site-packages/getsploit-0.3.3-py3.6.egg/getsploit/getsploit.py", line 204, in main
    vulners_lib.downloadGetsploitDb(os.path.join(DBPATH, "getsplit.db.zip"))
  File "/Users/none/.pyenv/versions/3.6.5/lib/python3.6/site-packages/getsploit-0.3.3-py3.6.egg/getsploit/getsploit.py", line 93, in downloadGetsploitDb
    zip_ref = zipfile.ZipFile(full_path, 'r')
  File "/Users/none/.pyenv/versions/3.6.5/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/Users/none/.pyenv/versions/3.6.5/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by vulnersCom** [comment]
Looks like networks issues.
Can’t reproduce.
