### ISSUE TITLE
API key entry not working

### ISSUE THREAD

**Issue by nicholasgpuig** [vulnersCom/getsploit#21]
After I enter my API key, this error message always shows up
`Traceback (most recent call last):
  File "$HOME/Library/Python/2.7/bin/getsploit", line 8, in <module>
    sys.exit(main())
  File "$HOME/Library/Python/2.7/lib/python/site-packages/getsploit/getsploit.py", line 189, in main
    vulners_lib = sploitVulners(api_key=api_key)
  File "$HOME/Library/Python/2.7/lib/python/site-packages/vulners/api.py", line 120, in __init__
    max_retries=retries)
`

**Comment by vulnersCom** [comment]
Please, provide more details.
What are you executing?

**Comment by Skyawesome73** [comment]
When I run the `getsploit` command by itself with no parameters, it asks for my vulners API key. When I copy and paste mine, the error shows up.
