### ISSUE TITLE
AttributeError: 'sploitVulners' object has no attribute '_Vulners__opener'

### ISSUE THREAD

**Issue by ghost** [vulnersCom/getsploit#23]
Hi,

When I tried to update getsploit database, I got this error:
```
/usr/local/lib/venvs/getsploit/lib/python3.9/site-packages/vulners/vulners.py:439: DeprecationWarning: Vulners is deprecated and will be removed in future release. Use VulnersApi instead.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/getsploit", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/venvs/getsploit/lib/python3.9/site-packages/getsploit/getsploit.py", line 195, in main
    vulners_lib._Vulners__opener.headers.update({'User-Agent': 'Vulners Getsploit %s' % __version__})
AttributeError: 'sploitVulners' object has no attribute '_Vulners__opener'
```

Any idea ?

**Comment by ndr3x** [comment]
Having the same issue...

**Comment by nair0lf32** [comment]
Facing the same issue very similar to issue #21. Same traceback errors when I try to enter my API key

**Comment by Pixelschleuder** [comment]
I found a fork that works fine because it ported getsploit to the new 2.0 API: [https://github.com/bbhunter/getsploit.git](https://github.com/bbhunter/getsploit.git)
